version: '3'

networks: 
  ntw-app:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - ../search:/app:delegated
      - ../awesome.yaml:/awesome.yaml:delegated
    working_dir: /app
    command: >
      sh -c "npm install &&
             DEBUG=search:* npm start"
    depends_on:
      - proxy
      - meilisearch
    networks:
      - ntw-app
  meilisearch:
    image: getmeili/meilisearch
    environment:
      - MEILI_API_KEY=masterKey
      - MEILI_MASTER_KEY=masterKey
    ports:
      - "7700:7700"
    depends_on:
      - proxy
    networks:
      - ntw-app
  proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:delegated
    networks:
      - ntw-app